description = "Build boost"
run = "./build.sh"

[input]
invariants = ["rustc -vV"]
env_vars = ["TEST"]

[[input.files]]
root = "."
filters = ["./src/**", "./Cargo.*"]
# not implemented yet, but on it's way...
ignores = ["./docs"]

[[output.files]]
root = "dist"
filters = ["dist/boost"]
