description = "Test boost"
run = "cargo test"

[[depends_on]]
name = "build"

[[depends_on]]
name = "build2"

[input]
invariants = ["rustc --vV"]

[[input.files]]
root = "."
filters = ["./src/**", "./Cargo.*"]
